SET NAMES 'UTF8';

UPDATE `locales_gameobject` SET `name_loc2` = "Disparu : caporal Keeshan", `name_loc3` = "Vermisst: Korporal Keeshan ", `name_loc6` = "Desaparecido: Cabo Keeshan ", `name_loc8` = "§±§â§à§á§Ñ§Ó§ê§Ú§Û §Ò§Ö§Ù §Ó§Ö§ã§ä§Ú: §Ü§Ñ§á§â§Ñ§Ý §¬§Ö§Ö§ê§Ñ§ß" WHERE `entry` = 1726; -- old - fr: Disparu !; de: Vermisst:; es: ?Desaparecido!; ru: §±§â§à§á§Ñ§Ý§Ú §Ò§Ö§Ù §Ó§Ö§ã§ä§Ú!
UPDATE `locales_gameobject` SET `name_loc2` = "Botte de plantes ", `name_loc3` = "Pflanzenb¨¹ndel ", `name_loc6` = "Paquete de plantas ", `name_loc8` = "§±§å§é§à§Ü §ä§â§Ñ§Ó" WHERE `entry` = 17282; -- old - fr: Cheveux de Bathran ; de: Bathranshaar ; es: Cabello de Bathran; ru: §¢§Ñ§ä§â§Ñ§ß§à§Ó §Ó§à§Ý§à§ã
UPDATE `locales_gameobject` SET `name_loc2` = "Hivernale", `name_loc3` = "Winterbiss ", `name_loc6` = "Invernalia ", `name_loc8` = "§®§à§â§à§Ù§ß§Ú§Ü" WHERE `entry` = 2044; -- old - fr: Dents de dragon; de: Drachenzahn; es: Dientes de drag¨®n ; ru: §¥§â§Ñ§Ü§à§ß§î§Ú §Ù§å§Ò§í 
UPDATE `locales_gameobject` SET `name_loc2` = "Avis de recherche : Lieutenant Tripecroc ", `name_loc3` = "GESUCHT: Leutnant Fangor ", `name_loc6` = "Se busca: Teniente Fangore ", `name_loc8` = "§²§Ñ§Ù§í§ã§Ü§Ú§Ó§Ñ§Ö§ä§ã§ñ: §Ý§Ö§Û§ä§Ö§ß§Ñ§ß§ä §¶§Ñ§ß§Ô§à§â " WHERE `entry` = 47; -- old - fr: Avis de recherche !; de: GESUCHT: ; es: ?Se busca!; ru: §²§à§Ù§í§ã§Ü! 
UPDATE `locales_gameobject` SET `name_loc2` = "Cartographie ", `name_loc3` = "Kartografie", `name_loc6` = "Cartograf¨ªa", `name_loc8` = "§¬§Ñ§â§ä§à§Ô§â§Ñ§æ§Ú§ñ " WHERE `entry` = 58626; -- old - fr: Arch¨¦ologie; de: Arch?ologie; es: Arqueolog¨ªa ; ru: §¡§â§ç§Ö§à§Ý§à§Ô§Ú§ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Tastebi¨¨re-cadeau de la f¨ºte des Brasseurs ", `name_loc3` = "Freibierkrug des Braufests ", `name_loc6` = "Jarra de degustaci¨®n de la Fiesta de la cerveza de obsequio", `name_loc8` = "§¢§Ö§ã§á§Ý§Ñ§ä§ß§à§Ö §á§Ú§Ó§à §·§Þ§Ö§Ý§î§ß§à§Ô§à §æ§Ö§ã§ä§Ú§Ó§Ñ§Ý§ñ " WHERE `entry` = 186189; -- old - fr: Tastebi¨¨re sans alcool de la f¨ºte des Brasseurs; de: Krug alkoholfreies Braufestbier; es: Jarra de degustaci¨®n de la Fiesta de la Cerveza sin alcohol ; ru: §¢§Ö§Ù§Ñ§Ý§Ü§à§Ô§à§Ý§î§ß§í§Û §á§â§à§Ò§ß§í§Û §ß§Ñ§á§Ú§ä§à§Ü §·§Þ§Ö§Ý§î§ß§à§Ô§à §æ§Ö§ã§ä§Ú§Ó§Ñ§Ý§ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Cage de Kraz ", `name_loc3` = "Kraz' K?fig", `name_loc6` = "Jaula de Kraz", `name_loc8` = "§¬§Ý§Ö§ä§Ü§Ñ §¬§â§Ñ§Ù§Ñ" WHERE `entry` = 187379; -- old - fr: Cage de Norkani; de: Norkanis K?fig ; es: Jaula de Norkani; ru: §¬§Ý§Ö§ä§Ü§Ñ §¯§à§â§Ü§Ñ§ß§Ú
UPDATE `locales_gameobject` SET `name_loc2` = "Cage de Harkor ", `name_loc3` = "Harkors K?fig", `name_loc6` = "Jaula de Harkor", `name_loc8` = "§¬§Ý§Ö§ä§Ü§Ñ §·§Ñ§â§Ü§à§â§Ñ" WHERE `entry` = 187378; -- old - fr: Cage de Bakkalzu ; de: Bakkalzus K?fig; es: Jaula de Bakkalzu ; ru: §¬§Ý§Ö§ä§Ü§Ñ §¢§Ñ§Ü§Ü§Ñ§Ý§î§Ù§å
UPDATE `locales_gameobject` SET `name_loc2` = "Paquet de Kraz ", `name_loc3` = "Krazs P?ckchen ", `name_loc6` = "Paquete de Kraz", `name_loc8` = "§´§ð§Ü §¬§â§Ñ§Ù§Ñ " WHERE `entry` = 186667; -- old - fr: Paquet de Norkani; de: Norkanis P?ckchen; es: Paquete de Norkani; ru: §´§ð§Ü §¯§à§â§Ü§Ñ§ß§Ú 
UPDATE `locales_gameobject` SET `name_loc2` = "Coffre de Kraz ", `name_loc3` = "Krazs Truhe", `name_loc6` = "Cofre de Kraz", `name_loc8` = "§³§å§ß§Õ§å§Ü §¬§â§Ñ§Ù§Ñ" WHERE `entry` = 186658; -- old - fr: Coffre de Norkani; de: Norkanis Truhe ; es: Cofre de Norkani; ru: §³§å§ß§Õ§å§Ü §¯§à§â§Ü§Ñ§ß§Ú
UPDATE `locales_gameobject` SET `name_loc2` = "Guilde des mineurs de la montagne profonde ", `name_loc3` = "Tiefenbergbaugilde ", `name_loc6` = "Gremio de miner¨ªa de Monta?ahonda", `name_loc8` = "§¤§Ú§Ý§î§Õ§Ú§ñ §Ô§à§â§ß§ñ§Ü§à§Ó §´§Ñ§Û§ß§à§Û §¤§à§â§í" WHERE `entry` = 143344; -- old - fr: Minage & joaillerie de la Montagne profonde; de: Tiefenberg Bergbau & Juwelierskunst; es: Miner¨ªa y joyer¨ªa de Montehondo ; ru: §¤§Ú§Ý§î§Õ§Ú§ñ §â§å§Õ§à§Ü§à§á§à§Ó §Ú §ð§Ó§Ö§Ý§Ú§â§à§Ó §´§Ö§Þ§ß§à§Û §¤§à§â§í
UPDATE `locales_gameobject` SET `name_loc2` = "Vase d'Ashli ", `name_loc3` = "Ashlis Vase", `name_loc6` = "Jarr¨®n de Ashli", `name_loc8` = "§£§Ñ§Ù§Ñ §¿§ê§Ý§Ú " WHERE `entry` = 186671; -- old - fr: Vase de Kasha; de: Kashas Vase; es: Jarr¨®n de Kasha ; ru: §£§Ñ§Ù§Ñ §¬§Ñ§Û§ê§Ú
UPDATE `locales_gameobject` SET `name_loc2` = "Cage d'Ashli ", `name_loc3` = "Ashlis K?fig ", `name_loc6` = "Jaula de Ashli ", `name_loc8` = "§¬§Ý§Ö§ä§Ü§Ñ §¿§ê§Ý§Ú " WHERE `entry` = 187380; -- old - fr: Cage de Kasha; de: Kashas K?fig ; es: Jaula de Kasha; ru: §¬§Ý§Ö§ä§Ü§Ñ §¬§Ñ§Û§ê§Ú
UPDATE `locales_gameobject` SET `name_loc2` = "Sac d'Ashli", `name_loc3` = "Ashlis Tasche", `name_loc6` = "Bolsa de Ashli ", `name_loc8` = "§³§å§Þ§Ü§Ñ §¿§ê§Ý§Ú" WHERE `entry` = 186672; -- old - fr: Sac de Kasha ; de: Kashas Tasche; es: Bolsa de Kasha; ru: §³§å§Þ§Ü§Ñ §¬§Ñ§Û§ê§Ú 
UPDATE `locales_gameobject` SET `name_loc2` = "Sacoche de Harkor", `name_loc3` = "Harkors Ranzen ", `name_loc6` = "Cartera de Harkor", `name_loc8` = "§³§å§Þ§Ü§Ñ §·§Ñ§â§Ü§à§â§Ñ " WHERE `entry` = 187021; -- old - fr: Sacoche de Bakkalzu; de: Bakkalzus Ranzen ; es: Cartera de Bakkalzu ; ru: §³§å§Þ§Ü§Ñ §¢§Ñ§Ü§Ü§Ñ§Ý§î§Ù§å 
UPDATE `locales_gameobject` SET `name_loc2` = "Malle de Tanzar", `name_loc3` = "Tanzars Koffer ", `name_loc6` = "Ba¨²l de Tanzar ", `name_loc8` = "§³§å§ß§Õ§å§é§à§Ü §´§Ñ§ß§Ù§Ñ§â§Ñ" WHERE `entry` = 186648; -- old - fr: Malle d'Hazlek ; de: Hazleks Koffer ; es: Ba¨²l de Hazlek; ru: §³§å§ß§Õ§å§é§à§Ü §·§Ñ§Ù§Ý§Ö§Ü§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Cage de Tanzar ", `name_loc3` = "Tanzars K?fig", `name_loc6` = "Jaula de Tanzar", `name_loc8` = "§¬§Ý§Ö§ä§Ü§Ñ §´§Ñ§ß§Ù§Ñ§â§Ñ" WHERE `entry` = 187377; -- old - fr: Cage d'Hazlek; de: Hazleks K?fig; es: Jaula de Hazlek ; ru: §¬§Ý§Ö§ä§Ü§Ñ §·§Ñ§Ù§Ý§Ö§Ü§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Forgeron de Baie-du-Butin", `name_loc3` = "Schmiede von Beutebucht", `name_loc6` = "Herrero de Bah¨ªa del Bot¨ªn ", `name_loc8` = "§¬§å§Ù§ß§Ö§è §±§Ú§â§Ñ§ä§ã§Ü§à§Û §¢§å§ç§ä§í" WHERE `entry` = 169967; -- old - fr: Forge; de: Schmied; es: Herrer¨ªa; ru: §¬§å§Ù§ß§Ú§è§Ñ 
UPDATE `locales_gameobject` SET `name_loc2` = "Tonneau de bi¨¨re de Harkor ", `name_loc3` = "Harkors Brauf?sschen ", `name_loc6` = "Barril de cerveza de Harkor", `name_loc8` = "§¢§à§é§à§ß§à§Ü §á§Ú§Ó§Ñ §·§Ñ§â§Ü§à§â§Ñ" WHERE `entry` = 186748; -- old - fr: Tonneau de bi¨¨re de Bakkalzu ; de: Bakkalzus Brauf?sschen ; es: Barril de cerveza de Bakkalzu ; ru: §¢§à§é§à§ß§à§Ü §á§Ú§Ó§Ñ §¢§Ñ§Ü§Ü§Ñ§Ý§î§Ù§å
UPDATE `locales_gameobject` SET `name_loc2` = "Caisses de ravitaillement de la Crois¨¦e", `name_loc3` = "Vorratskisten des Wegekreuzes", `name_loc6` = "Cajones de suministros de El Cruce ", `name_loc8` = "§Á§ë§Ú§Ü§Ú §ã §á§â§Ú§á§Ñ§ã§Ñ§Þ§Ú §Õ§Ý§ñ §±§Ö§â§Ö§Ü§â§Ö§ã§ä§Ü§Ñ " WHERE `entry` = 175708; -- old - fr: Caisse de ravitaillement de la Crois¨¦e ; de: Vorratskiste des Wegekreuzes ; es: Caj¨®n de suministros de El Cruce; ru: §Á§ë§Ú§Ü §ã §á§â§Ú§á§Ñ§ã§Ñ§Þ§Ú §±§Ö§â§Ö§Ü§â§Ö§ã§ä§Ü§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Banni¨¨re de Karang ", `name_loc3` = "Karangs Banner ", `name_loc6` = "Estandarte de Karang ", `name_loc8` = "§©§ß§Ñ§Þ§ñ §¬§Ñ§â§Ñ§ß§Ô§Ñ " WHERE `entry` = 178205; -- old - fr: Banni¨¨re de Senani ; de: Senanis Banner ; es: Estandarte de Senani; ru: §©§ß§Ñ§Þ§ñ §³§Ö§ß§Ñ§ß§Ú
UPDATE `locales_gameobject` SET `name_loc2` = "Fus¨¦e de feu d'artifice, Promotion ", `name_loc3` = "Feuerwerksrakete, Aktion ", `name_loc6` = "Cohete de fuegos artificiales, promoci¨®n ", `name_loc8` = "§²§Ñ§Ü§Ö§ä§Ñ §æ§Ö§Û§Ö§â§Ó§Ö§â§Ü§Ñ, §á§â§à§Õ§Ó§Ú§Ø§Ö§ß§Ú§Ö" WHERE `entry` = 181886; -- old - fr: Fus¨¦e de feu d'artifice violet ; de: Lila Feuerwerksrakete; es: Cohete de fuegos artificiales morado; ru: §­§Ú§Ý§à§Ó§Ñ§ñ §â§Ñ§Ü§Ö§ä§Ñ §æ§Ö§Û§Ö§â§Ó§Ö§â§Ü§Ñ 
UPDATE `locales_gameobject` SET `name_loc2` = "Bois contamin¨¦ ", `name_loc3` = "Besudeltes Holz", `name_loc6` = "Madera m¨¢cula", `name_loc8` = "§¤§ß§Ú§Ý§à§Ö §Õ§Ö§â§Ö§Ó§à " WHERE `entry` = 181916; -- old - fr: Bois gangren¨¦ de Satyrnaar ; de: Verdorbenes Satyrnaarholz; es: Madera vil de Satyrnaar ; ru: §³§Ó§ñ§Ù§Ü§Ñ §à§ã§Ü§Ó§Ö§â§ß§Ö§ß§ß§à§Û §Õ§â§Ö§Ó§Ö§ã§Ú§ß§í §³§Ñ§ä§Ú§â§ß§Ñ§Ñ§â§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Bateau vers Auberdine", `name_loc3` = "Schiff nach Auberdine", `name_loc6` = "Barco a Auberdine", `name_loc8` = "§¬§à§â§Ñ§Ò§Ý§î §Ó §¡§å§Ò§Ö§â§Õ§Ú§ß" WHERE `entry` = 181985; -- old - fr: Bateau vers Rut'Theran ; de: Schiff nach Rut'Theran ; es: Barco a la Aldea Rut'theran ; ru: §¬§à§â§Ñ§Ò§Ý§î §Ó §Õ§Ö§â§Ö§Ó§ß§ð §²§å§ä'§´§Ö§â§Ñ§ß 
UPDATE `locales_gameobject` SET `name_loc2` = "Enchantement ", `name_loc3` = "Verzauberkunst ", `name_loc6` = "Encantamiento", `name_loc8` = "§¯§Ñ§Ý§à§Ø§Ö§ß§Ú§Ö §é§Ñ§â " WHERE `entry` = 183875; -- old - fr: Enchantement & Calligraphie; de: Verzauberkunst & Inschriftenkunde; es: Encantamiento e inscripci¨®n ; ru: §¯§Ñ§Ý§à§Ø§Ö§ß§Ú§Ö §é§Ñ§â §Ú §ß§Ñ§é§Ö§â§ä§Ñ§ß§Ú§Ö
UPDATE `locales_gameobject` SET `name_loc2` = "Fl¨¨che givrante I", `name_loc3` = "Eisk?ltepfeil I", `name_loc6` = "Flecha helada I", `name_loc8` = "§©§Ñ§Þ§à§â§Ñ§Ø§Ú§Ó§Ñ§ð§ë§Ñ§ñ §ã§ä§â§Ö§Ý§Ñ I " WHERE `entry` = 193771; -- old - fr: Pi¨¨ge givrant; de: Eisk?ltefalle; es: Trampa congelante ; ru: §©§Ñ§Þ§à§â§Ñ§Ø§Ú§Ó§Ñ§ð§ë§Ñ§ñ §Ý§à§Ó§å§ê§Ü§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Canon de l'Alliance", `name_loc3` = "Allianz Kannone", `name_loc6` = "Ca?¨®n de la alianza", `name_loc8` = "§±§å§ê§Ü§Ñ §¡§Ý§î§ñ§ß§ã§Ñ " WHERE `entry` = 185122; -- old - fr: Ogres de la Masse-sanglante en grande conversation ; de: Sich unterhaltende Oger der Blutschl?ger ; es: Ogros de Machacasangre hablando ; ru: §¢§Ö§ã§Ö§Õ§å§ð§ë§Ú§Ö §à§Ô§â§í §Ú§Ù §Ü§Ý§Ñ§ß§Ñ §¬§â§à§Ó§Ñ§Ó§à§Ô§à §®§à§Ý§à§ä§Ñ 
UPDATE `locales_gameobject` SET `name_loc2` = "Tram ", `name_loc3` = "U-Bahn ", `name_loc6` = "Tranv¨ªa Subterr¨¢neo", `name_loc8` = "§±§à§Õ§Ù§Ö§Þ§Ü§Ñ" WHERE `entry` = 176086; -- old - fr: Cuirasse couverte de runes inachev¨¦e ; de: Ungeschmiedete runenbedeckte Brustplatte ; es: Coraza cubierta de runas sin forjar ; ru: §©§Ñ§Ô§à§ä§à§Ó§Ü§Ñ §â§å§ß§Ú§é§Ö§ã§Ü§à§Û §Ü§Ú§â§Ñ§ã§í 
UPDATE `locales_gameobject` SET `name_loc2` = "Fleur de peste ", `name_loc3` = "Pestbl¨¹te", `name_loc6` = "Flor de peste", `name_loc8` = "§¹§å§Þ§à§è§Ó§Ö§ä" WHERE `entry` = 176641; -- old - fr: Chagrinelle; de: Trauermoos ; es: Musgopena ; ru: §±§Ö§é§Ñ§Ý§î-§ä§â§Ñ§Ó§Ñ
 
UPDATE `locales_gameobject` SET `name_loc2` = "La Lune la Vall¨¦e", `name_loc3` = "Mond ¨¹ber dem Tal", `name_loc8` = "§­§å§ß§Ñ §ß§Ñ§Õ §Õ§à§Ý§Ú§ß§à§Û" WHERE `entry` = 57; -- old - fr: Tablette de savoir scalp-rouge ; de: Schrifttafel der Blutskalpe; ru: §­§Ö§Ô§Ö§ß§Õ§í §Ú §á§â§Ö§Õ§Ñ§ß§Ú§ñ §á§Ý§Ö§Þ§Ö§ß§Ú §¬§â§à§Ó§Ñ§Ó§à§Ô§à §³§Ü§Ñ§Ý§î§á§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Fleur de peste", `name_loc3` = "Pestbl¨¹te", `name_loc8` = "§¹§å§Þ§à§è§Ó§Ö§ä" WHERE `entry` = 176587; -- old - fr: Chagrinelle; de: Trauermoos ; ru: §±§Ö§é§Ñ§Ý§î-§ä§â§Ñ§Ó§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Banni¨¨re elfe de sang", `name_loc6` = "Estandarte de los elfos de sangre", `name_loc8` = "§©§ß§Ñ§Þ§ñ §ï§Ý§î§æ§à§Ó §Ü§â§à§Ó§Ú" WHERE `entry` = 185106; -- old - fr: PVP HOLIDAY (H) EotS ; es: PVP HOLIDAY (H) EotS; ru: PVP HOLIDAY (H) EotS
UPDATE `locales_gameobject` SET `name_loc2` = "Boulet et cha?ne de Knot", `name_loc6` = "Bola y cadena de Knot", `name_loc8` = "§º§Ñ§â §Ú §è§Ö§á§î §µ§Ù§Ù§Ý§Ñ" WHERE `entry` = 179511; -- old - fr: Boulet et cha?ne de Nou¨¦ ; es: Knot's Ball and Chain ; ru: §Á§Õ§â§à §ß§Ñ §è§Ö§á§Ú §µ§Ù§Ù§Ý§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Drapeau chanteguerre", `name_loc6` = "Bandera Grito de Guerra", `name_loc8` = "§¶§Ý§Ñ§Ô §±§Ö§ã§ß§Ú §£§à§Û§ß§í" WHERE `entry` = 179786; -- old - fr: Drapeau de la Horde; es: Bandera de la Horda ; ru: §¶§Ý§Ñ§Ô §°§â§Õ§í 
UPDATE `locales_gameobject` SET `name_loc2` = "Drapeau d'Aile-argent", `name_loc6` = "Bandera Ala de Plata", `name_loc8` = "§¶§Ý§Ñ§Ô §³§Ö§â§Ö§Ò§â§ñ§ß§í§ç §¬§â§í§Ý§î§Ö§Ó" WHERE `entry` = 179785; -- old - fr: Drapeau de l'Alliance; es: Bandera de la Alianza ; ru: §¶§Ý§Ñ§Ô §¡§Ý§î§ñ§ß§ã§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Drapeau d'Aile-argent", `name_loc6` = "Bandera Ala de Plata", `name_loc8` = "§¶§Ý§Ñ§Ô §³§Ö§â§Ö§Ò§â§ñ§ß§í§ç §¬§â§í§Ý§î§Ö§Ó" WHERE `entry` = 179830; -- old - fr: Drapeau de l¡¯Alliance; es: Bandera de la Alianza ; ru: §¶§Ý§Ñ§Ô §¡§Ý§î§ñ§ß§ã§Ñ
UPDATE `locales_gameobject` SET `name_loc2` = "Drapeau chanteguerre", `name_loc6` = "Bandera Grito de Guerra", `name_loc8` = "§¶§Ý§Ñ§Ô §±§Ö§ã§ß§Ú §£§à§Û§ß§í" WHERE `entry` = 179831; -- old - fr: Drapeau de la Horde; es: Bandera de la Horda ; ru: §¶§Ý§Ñ§Ô §°§â§Õ§í 
UPDATE `locales_gameobject` SET `name_loc2` = "Brasero antique", `name_loc6` = "Bland¨®n antiguo", `name_loc8` = "§¥§â§Ö§Ó§ß§ñ§ñ §Ø§Ñ§â§à§Ó§ß§ñ" WHERE `entry` = 20807; -- old - fr: [P¨¦RIM¨¦]Brasero antique; es: [Deprecated for 4.x]Bland¨®n antiguo ; ru: [Deprecated for 4.x]Ancient Brazier 
UPDATE `locales_gameobject` SET `name_loc2` = "D¨¦combres de chariot explosif", `name_loc6` = "Restos del coche cohete", `name_loc8` = "§°§Ò§Ý§à§Þ§Ü§Ú §Ò§à§Ý§Ú§Õ§Ñ" WHERE `entry` = 19868; -- old - fr: [INUTILIS¨¦ pour 4.x] D¨¦combres de chariot explosif ; es: [Deprecated for 4.x]Restos del coche cohete ; ru: [Deprecated for 4.x]Rocket Car Rubble 
UPDATE `locales_gameobject` SET `name_loc2` = "D¨¦combres de chariot explosif", `name_loc6` = "Restos del coche cohete", `name_loc8` = "§°§Ò§Ý§à§Þ§Ü§Ú §Ò§à§Ý§Ú§Õ§Ñ" WHERE `entry` = 19869; -- old - fr: [INUTILIS¨¦ pour 4.x] D¨¦combres de chariot explosif ; es: [Deprecated for 4.x]Restos del coche cohete ; ru: [Deprecated for 4.x]Rocket Car Rubble 
UPDATE `locales_gameobject` SET `name_loc2` = "D¨¦combres de chariot explosif", `name_loc6` = "Restos del coche cohete", `name_loc8` = "§°§Ò§Ý§à§Þ§Ü§Ú §Ò§à§Ý§Ú§Õ§Ñ" WHERE `entry` = 19870; -- old - fr: [INUTILIS¨¦ pour 4.x] D¨¦combres de chariot explosif ; es: [Deprecated for 4.x]Restos del coche cohete ; ru: [Deprecated for 4.x]Rocket Car Rubble 
UPDATE `locales_gameobject` SET `name_loc2` = "D¨¦combres de chariot explosif", `name_loc6` = "Restos del coche cohete", `name_loc8` = "§°§Ò§Ý§à§Þ§Ü§Ú §Ò§à§Ý§Ú§Õ§Ñ" WHERE `entry` = 19871; -- old - fr: [INUTILIS¨¦ pour 4.x] D¨¦combres de chariot explosif ; es: [Deprecated for 4.x]Restos del coche cohete ; ru: [Deprecated for 4.x]Rocket Car Rubble 
UPDATE `locales_gameobject` SET `name_loc2` = "D¨¦combres de chariot explosif", `name_loc6` = "Restos del coche cohete", `name_loc8` = "§°§Ò§Ý§à§Þ§Ü§Ú §Ò§à§Ý§Ú§Õ§Ñ" WHERE `entry` = 19872; -- old - fr: [INUTILIS¨¦ pour 4.x] D¨¦combres de chariot explosif ; es: [Deprecated for 4.x]Restos del coche cohete ; ru: [Deprecated for 4.x]Rocket Car Rubble 
UPDATE `locales_gameobject` SET `name_loc2` = "D¨¦combres de chariot explosif", `name_loc6` = "Restos del coche cohete", `name_loc8` = "§°§Ò§Ý§à§Þ§Ü§Ú §Ò§à§Ý§Ú§Õ§Ñ" WHERE `entry` = 19873; -- old - fr: [INUTILIS¨¦ pour 4.x] D¨¦combres de chariot explosif ; es: [Deprecated for 4.x]Restos del coche cohete ; ru: [Deprecated for 4.x]Rocket Car Rubble 
UPDATE `locales_gameobject` SET `name_loc3` = "Bergbau", `name_loc6` = "Miner¨ªa", `name_loc8` = "§¤§à§â§ß§à§Ö §Õ§Ö§Ý§à" WHERE `entry` = 58620; -- old - de: Bergbau & Juwelierskunst ; es: Miner¨ªa y joyer¨ªa ; ru: §¤§à§â§ß§à§Ö §Ú §ð§Ó§Ö§Ý§Ú§â§ß§à§Ö §Õ§Ö§Ý§à 
UPDATE `locales_gameobject` SET `name_loc3` = "Auberdine Mondbrunnen", `name_loc6` = "Poza de la Luna de Auberdine", `name_loc8` = "§¡§å§Ò§Ö§â§Õ§Ú§ß §­§å§ß§ß§í§Û §Ü§à§Ý§à§Õ§Ö§è" WHERE `entry` = 174795; -- old - de: Wachposten der Mondfederfeste; es: Puesto de vigilancia de Plumaluna ; ru: §©§Ñ§ã§ä§Ñ§Ó§Ñ §°§á§Ö§â§Ö§ß§ß§à§Û §­§å§ß§í
UPDATE `locales_gameobject` SET `name_loc3` = "Axtrad", `name_loc6` = "Engranajes ligeros", `name_loc8` = "§ª§ß§ã§ä§â§å§Þ§Ö§ß§ä §ä§à§á§à§â§Ñ" WHERE `entry` = 194577; -- old - de: T¨¹r 02 ; es: Door 02 ; ru: §¥§Ó§Ö§â§î 2 
UPDATE `locales_gameobject` SET `name_loc2` = "Biblioth¨¨que ¨¦trange", `name_loc3` = "Seltsamer B¨¹cherschrank", `name_loc6` = "Estanter¨ªa extra?a" WHERE `entry` = 184453; -- old - fr: Biblioth¨¨que ¨¦nigmatiquede: Verbl¨¹ffendes B¨¹cherregal; es: Estanter¨ªa desconcertante
